GET http://localhost:5000/courses

###
GET http://localhost:5000/courses/24

###
POST http://localhost:5000/courses
Content-Type: application/json

{
    "name": "hahah",
    "teacher": "hihihih"
}

###
PATCH  http://localhost:5000/courses/24

{
  "name": "Pemro SQL",
  "teacher": "Bapak Arif",
}

###
DELETE  http://localhost:5000/courses/5