GET http://localhost:5000/courses

###
GET http://localhost:5000/courses/27

###
POST http://localhost:5000/courses
Content-Type: application/json

{
    "name": "hahah",
    "teacher": "hihihih"
}

###
PATCH http://localhost:5000/courses/27
Content-Type: application/application/json

{
    "name": "hahah",
    "teacher": "hihihih"
}

###
DELETE  http://localhost:5000/courses/28

